
name: Java CI with Gradle

on:
  push:
    branches:
      - "main"
      - "update-github-actions"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Grant execute permissions for Gradle wrapper
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Get JAR path
      id: jar-path
      run: |
        path=$(find ${{ github.workspace }}/lwjgl3/build/libs -name "*.jar" -print -quit)
        echo "::set-output name=path::$path"
#        echo "JAR_FILE_NAME=$JAR_FILE_NAME" >> $GITHUB_ENV

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: $(basename ${{ steps.jar-path.outputs.path }})
        path: ${{ steps.jar-path.outputs.path }}
