
name: Java CI with Gradle

on:
  push:
    branches:
      - "main"
      - "42-code-format-style-tests" # todo remove after testing
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Grant execute permissions for Gradle wrapper
      run: chmod +x ./gradlew

    - name: Run Checkstyle
      run: ./gradlew checkstyleMain

    - name: Aggregate Checkstyle Reports
      if: always() # This ensures the Checkstyle reports are aggregated regardless of whether checkstyle fails the build
      run: ./gradlew aggregateCheckstyleReports

    - name: Upload Checkstyle Report
      if: always() # This ensures the Checkstyle reports is uploaded regardless of whether checkstyle fails the build
      uses: actions/upload-artifact@v4
      with:
        name: checkstyle-report
        path: ./core/build/reports/checkstyle/*

    - name: Build with Gradle
      run: ./gradlew build

    - name: Find JAR File
      id: jar-path
      run: |
        JAR_PATH=$(find ${{ github.workspace }}/lwjgl3/build/libs -name "*.jar" -print -quit)
        echo "JAR_FILENAME=$(basename $JAR_PATH)" >> $GITHUB_OUTPUT
        echo "JAR_PATH=$JAR_PATH" >> $GITHUB_OUTPUT

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.jar-path.outputs.JAR_FILENAME}}
        path: ${{ steps.jar-path.outputs.JAR_PATH }}
